name: Run tests

on: [pull_request]

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
            node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Run prettier
        run: npx prettier --check **/*.ts

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: ecommerce
          POSTGRES_USER: ecommerce
          POSTGRES_DB: ecommerce
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
            node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Migrate
        run: npm run ci:migrate
        env:
          DATABASE_URL: postgresql://ecommerce:ecommerce@localhost:5432/ecommerce?schema=public

      - name: Run tests
        run: npm run ci:test
        env:
          DATABASE_URL: postgresql://ecommerce:ecommerce@localhost:5432/ecommerce?schema=public
